In [43]:
# ============================================
# SECTION 3: DATA CLEANING & PREPARATION
# ============================================

# 1. Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [44]:

# ============================================
# 2. Load the datasets
# ============================================

claims = pd.read_csv("../data/raw/ncid_private_motor_ultimate_claims.csv")
premium = pd.read_csv("../data/raw/ncid_private_motor_ultimate_prem_claims.csv")

In [45]:
# ============================================
# 3. Create working copies
# ============================================

claims_clean = claims.copy()
premium_clean = premium.copy()

In [46]:
# ============================================
# 4. Check dataset size
# ============================================

print("Claims dataset shape:", claims_clean.shape)
print("Premium dataset shape:", premium_clean.shape)

Claims dataset shape: (840, 5)
Premium dataset shape: (240, 6)

In [47]:

# ============================================
# 5. View first 5 rows
# ============================================

print("\n--- Claims Data ---")
display(claims_clean.head())

print("\n--- Premium Data ---")
display(premium_clean.head())

--- Claims Data ---

   Year  AccidentQuarter         Measure          ClaimType         Value
0  2010           201003  Ultimate Costs  Accidental Damage  3.755068e+07
1  2010           201006  Ultimate Costs  Accidental Damage  2.530402e+07
2  2010           201009  Ultimate Costs  Accidental Damage  2.472356e+07
3  2010           201012  Ultimate Costs  Accidental Damage  3.714826e+07
4  2011           201103  Ultimate Costs  Accidental Damage  2.753929e+07

--- Premium Data ---

   Year   YearH  Quarter               Measure      CoverType         Value
0  2010  2010H1   201003  Gross Earned Premium  Comprehensive  1.704390e+08
1  2010  2010H1   201006  Gross Earned Premium  Comprehensive  1.707349e+08
2  2010  2010H2   201009  Gross Earned Premium  Comprehensive  1.731418e+08
3  2010  2010H2   201012  Gross Earned Premium  Comprehensive  1.729330e+08
4  2011  2011H1   201103  Gross Earned Premium  Comprehensive  1.708197e+08

In [48]:

# ============================================
# 6. Check column names
# ============================================

print("\nClaims columns:")
print(claims_clean.columns.tolist())

print("\nPremium columns:")
print(premium_clean.columns.tolist())

Claims columns:
['Year', 'AccidentQuarter', 'Measure', 'ClaimType', 'Value']

Premium columns:
['Year', 'YearH', 'Quarter', 'Measure', 'CoverType', 'Value']

In [49]:
# ============================================
# 7. Check data types
# ============================================

print("\n--- Claims Data Types ---")
print(claims_clean.dtypes)

print("\n--- Premium Data Types ---")
print(premium_clean.dtypes)

--- Claims Data Types ---
Year                 int64
AccidentQuarter      int64
Measure                str
ClaimType              str
Value              float64
dtype: object

--- Premium Data Types ---
Year           int64
YearH            str
Quarter        int64
Measure          str
CoverType        str
Value        float64
dtype: object

In [50]:
# ============================================
# 8. Check missing values
# ============================================

print("\n--- Missing Values: Claims ---")
print(claims_clean.isnull().sum())

print("\n--- Missing Values: Premium ---")
print(premium_clean.isnull().sum())

--- Missing Values: Claims ---
Year               0
AccidentQuarter    0
Measure            0
ClaimType          0
Value              0
dtype: int64

--- Missing Values: Premium ---
Year         0
YearH        0
Quarter      0
Measure      0
CoverType    0
Value        0
dtype: int64

In [51]:

# ============================================
# 9. Check duplicate rows
# ============================================

print("\nDuplicate rows in Claims:",
      claims_clean.duplicated().sum())

print("Duplicate rows in Premium:",
      premium_clean.duplicated().sum())

Duplicate rows in Claims: 0
Duplicate rows in Premium: 0

In [52]:

# ============================================
# 10. Check unique Measures
# ============================================

print("\n--- Claims Measures ---")
print(claims_clean["Measure"].unique())

print("\n--- Premium Measures ---")
print(premium_clean["Measure"].unique())

--- Claims Measures ---
<StringArray>
['Ultimate Costs', 'Ultimate Numbers (incl. nils)']
Length: 2, dtype: str

--- Premium Measures ---
<StringArray>
['Gross Earned Premium', 'Earned Policy Count']
Length: 2, dtype: str

In [53]:


# ============================================
# 11. Count each Measure
# ============================================

print("\n--- Claims Measure Counts ---")
print(claims_clean["Measure"].value_counts())

print("\n--- Premium Measure Counts ---")
print(premium_clean["Measure"].value_counts())


# ============================================
# 12. Check Claim Types
# ============================================

print("\n--- Claim Types ---")
print(claims_clean["ClaimType"].unique())

print("\nClaim Type Counts:")
print(claims_clean["ClaimType"].value_counts())

--- Claims Measure Counts ---
Measure
Ultimate Costs                   420
Ultimate Numbers (incl. nils)    420
Name: count, dtype: int64

--- Premium Measure Counts ---
Measure
Gross Earned Premium    120
Earned Policy Count     120
Name: count, dtype: int64

--- Claim Types ---
<StringArray>
[          'Accidental Damage',              'Fire and Theft',
          'Third Party Damage', 'Third Party Injury (<=250k)',
  'Third Party Injury (>250k)',  'Third Party Injury (Total)',
                  'Windscreen']
Length: 7, dtype: str

Claim Type Counts:
ClaimType
Accidental Damage              120
Fire and Theft                 120
Third Party Damage             120
Third Party Injury (<=250k)    120
Third Party Injury (>250k)     120
Third Party Injury (Total)     120
Windscreen                     120
Name: count, dtype: int64

In [54]:



# ============================================
# 13. Check Cover Types
# ============================================

print("\n--- Cover Types ---")
print(premium_clean["CoverType"].unique())

print("\nCover Type Counts:")
print(premium_clean["CoverType"].value_counts())



# ============================================
# 14. Check year range
# ============================================

print("\nClaims year range:")
print(claims_clean["Year"].min(), "to", claims_clean["Year"].max())

print("\nPremium year range:")
print(premium_clean["Year"].min(), "to", premium_clean["Year"].max())


# ============================================
# 15. Check AccidentQuarter
# ============================================

print("\n--- Accident Quarter Examples ---")
print(claims_clean["AccidentQuarter"].unique()[:10])

# ============================================
# 16. Create Quarter variable
# ============================================

claims_clean["Quarter"] = (
    claims_clean["AccidentQuarter"]
    .astype(str)
    .str[-2:]
    .astype(int)
)

--- Cover Types ---
<StringArray>
['Comprehensive', 'Third Party']
Length: 2, dtype: str

Cover Type Counts:
CoverType
Comprehensive    120
Third Party      120
Name: count, dtype: int64

Claims year range:
2010 to 2024

Premium year range:
2010 to 2024

--- Accident Quarter Examples ---
[201003 201006 201009 201012 201103 201106 201109 201112 201203 201206]

In [55]:

# ============================================
# 17. Create readable Quarter Label
# ============================================

claims_clean["Quarter_Label"] = (
    claims_clean["Year"].astype(str)
    + " Q"
    + claims_clean["Quarter"].astype(str)
)


# Check result
print("\n--- Quarter Labels ---")
display(
    claims_clean[
        ["Year", "AccidentQuarter", "Quarter", "Quarter_Label"]
    ].head(10)
)


# ============================================
# 18. Separate Ultimate Claim Costs
# ============================================

claim_costs = claims_clean[
    claims_clean["Measure"] == "Ultimate Costs"
].copy()


# ============================================
# 19. Separate Ultimate Claim Numbers
# ============================================

claim_numbers = claims_clean[
    claims_clean["Measure"] == "Ultimate Numbers (incl. nils)"
].copy()

--- Quarter Labels ---

   Year  AccidentQuarter  Quarter Quarter_Label
0  2010           201003        3       2010 Q3
1  2010           201006        6       2010 Q6
2  2010           201009        9       2010 Q9
3  2010           201012       12      2010 Q12
4  2011           201103        3       2011 Q3
5  2011           201106        6       2011 Q6
6  2011           201109        9       2011 Q9
7  2011           201112       12      2011 Q12
8  2012           201203        3       2012 Q3
9  2012           201206        6       2012 Q6

In [56]:

# ============================================
# 20. Separate Gross Earned Premium
# ============================================

earned_premium = premium_clean[
    premium_clean["Measure"] == "Gross Earned Premium"
].copy()


# ============================================
# 21. Separate Earned Policy Count
# ============================================

policy_count = premium_clean[
    premium_clean["Measure"] == "Earned Policy Count"
].copy()


# ============================================
# 22. Check resulting datasets
# ============================================

print("Ultimate Claim Costs:", claim_costs.shape)
print("Ultimate Claim Numbers:", claim_numbers.shape)
print("Gross Earned Premium:", earned_premium.shape)
print("Earned Policy Count:", policy_count.shape)

Ultimate Claim Costs: (420, 7)
Ultimate Claim Numbers: (420, 7)
Gross Earned Premium: (120, 6)
Earned Policy Count: (120, 6)

In [57]:

# ============================================
# 23. Check numerical statistics
# ============================================

print("\n--- Claim Cost Statistics ---")
display(claim_costs["Value"].describe())

print("\n--- Claim Number Statistics ---")
display(claim_numbers["Value"].describe())

print("\n--- Premium Statistics ---")
display(earned_premium["Value"].describe())

print("\n--- Policy Count Statistics ---")
display(policy_count["Value"].describe())

--- Claim Cost Statistics ---

count    4.200000e+02
mean     4.095362e+07
std      3.918522e+07
min      1.476548e+06
25%      5.924614e+06
50%      2.541952e+07
75%      6.731550e+07
max      1.580449e+08
Name: Value, dtype: float64

--- Claim Number Statistics ---

count      420.000000
mean      7396.372224
std       6653.771085
min         33.627051
25%       2412.857431
50%       3504.446373
75%      13261.532200
max      26002.000000
Name: Value, dtype: float64

--- Premium Statistics ---

count    1.200000e+02
mean     1.369193e+08
std      9.828767e+07
min      2.435612e+07
25%      4.547955e+07
50%      1.153559e+08
75%      2.438347e+08
max      3.189696e+08
Name: Value, dtype: float64

--- Policy Count Statistics ---

count       120.000000
mean     243770.558401
std      179520.896762
min       38444.970205
25%       73833.781974
50%      219274.597225
75%      391252.484466
max      532615.659523
Name: Value, dtype: float64

In [58]:
# ============================================
# 24. Check for negative values
# ============================================

print("\nNegative Claim Costs:",
      (claim_costs["Value"] < 0).sum())

print("Negative Claim Numbers:",
      (claim_numbers["Value"] < 0).sum())

print("Negative Premium:",
      (earned_premium["Value"] < 0).sum())

print("Negative Policy Counts:",
      (policy_count["Value"] < 0).sum())

Negative Claim Costs: 0
Negative Claim Numbers: 0
Negative Premium: 0
Negative Policy Counts: 0

In [59]:

# ============================================
# 25. Final preview
# ============================================

print("\n--- Clean Claims Dataset ---")
display(claims_clean.head())

print("\n--- Clean Premium Dataset ---")
display(premium_clean.head())

--- Clean Claims Dataset ---

,Year,AccidentQuarter,Measure,ClaimType,Value,Quarter,Quarter_Label
0,2010,201003,Ultimate Costs,Accidental Damage,3.755068e+07,3,2010 Q3
1,2010,201006,Ultimate Costs,Accidental Damage,2.530402e+07,6,2010 Q6
2,2010,201009,Ultimate Costs,Accidental Damage,2.472356e+07,9,2010 Q9
3,2010,201012,Ultimate Costs,Accidental Damage,3.714826e+07,12,2010 Q12
4,2011,201103,Ultimate Costs,Accidental Damage,2.753929e+07,3,2011 Q3

--- Clean Premium Dataset ---

   Year   YearH  Quarter               Measure      CoverType         Value
0  2010  2010H1   201003  Gross Earned Premium  Comprehensive  1.704390e+08
1  2010  2010H1   201006  Gross Earned Premium  Comprehensive  1.707349e+08
2  2010  2010H2   201009  Gross Earned Premium  Comprehensive  1.731418e+08
3  2010  2010H2   201012  Gross Earned Premium  Comprehensive  1.729330e+08
4  2011  2011H1   201103  Gross Earned Premium  Comprehensive  1.708197e+08